# Generated by Django 4.2.15 on 2025-04-19 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0012_perspective_description_1_perspective_description_2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotatorPerspective",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Data de Criação")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Data de Atualização")),
                (
                    "annotator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perspectives",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Anotador",
                    ),
                ),
                (
                    "perspective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotators",
                        to="projects.perspective",
                        verbose_name="Perspectiva",
                    ),
                ),
            ],
            options={
                "verbose_name": "Associação Anotador-Perspectiva",
                "verbose_name_plural": "Associações Anotadores-Perspectivas",
                "unique_together": {("annotator", "perspective")},
            },
        ),
    ]
