# Generated by Django 4.2.15 on 2025-04-19 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0013_annotatorperspective"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annotatorperspective",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="annotatorperspective",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="annotatorperspective",
            name="annotator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotator_perspectives",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="annotatorperspective",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="annotatorperspective",
            name="perspective",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotator_perspective",
                to="projects.perspective",
            ),
        ),
        migrations.AddConstraint(
            model_name="annotatorperspective",
            constraint=models.UniqueConstraint(
                fields=("annotator", "perspective"), name="unique_annotator_perspective"
            ),
        ),
        migrations.RemoveField(
            model_name="annotatorperspective",
            name="updated_at",
        ),
    ]
